import type { MssqlDatabase } from '../../src/model/database.js';

/**
 * Codepoint-ordered comparison. Never `localeCompare`: these tests assert
 * determinism, so the sort itself must not depend on the host locale.
 */
function byText(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function sortBy<T>(items: readonly T[], key: (item: T) => string): T[] {
  return [...items].sort((a, b) => byText(key(a), key(b)));
}

/**
 * SQL Server invents a name for a constraint declared without one, and the
 * generated suffix is instance/object-id specific
 * (`DF__AllTypes__ColBit__3A4CA8FD`), so a restored copy legitimately gets a
 * different one. Collapse only those to a placeholder; a name the fixture
 * gave explicitly must still be compared exactly, since preserving it is a
 * documented guarantee of this package.
 */
const AUTO_GENERATED_NAME = /^(DF|PK|UQ|CK|FK)__.*__[0-9A-F]{8}$/;

export function normalizeConstraintName(name: string): string {
  return AUTO_GENERATED_NAME.test(name) ? `${name.slice(0, 2)}__<auto-generated>` : name;
}

/**
 * Projects an introspected `MssqlDatabase` onto a comparable shape: drops
 * everything that legitimately differs between two databases holding the
 * same logical schema (the database name, `object_id`s, create/modify
 * timestamps, auto-generated constraint names, sequence *current* value),
 * and sorts every collection by a stable key so iteration order cannot
 * affect the result.
 *
 * What remains is exactly what a correct dump/restore must reproduce, so a
 * deep-equality failure against this projection is a real semantic
 * regression rather than incidental noise.
 */
export function normalizeDatabase(database: MssqlDatabase): unknown {
  return {
    collationName: database.collationName,
    compatibilityLevel: database.compatibilityLevel,

    schemas: sortBy(database.schemas, s => s.schemaName).map(schema => ({
      schemaName: schema.schemaName,
      ownerName: schema.ownerName,
    })),

    tables: sortBy(database.tables, t => `${t.schemaName}.${t.pureName}`).map(table => ({
      schemaName: table.schemaName,
      pureName: table.pureName,
      isMemoryOptimized: table.isMemoryOptimized,
      durability: table.durability,
      isSystemVersioned: table.isSystemVersioned,
      historyTableSchemaName: table.historyTableSchemaName,
      historyTablePureName: table.historyTablePureName,
      columns: [...table.columns]
        .sort((a, b) => a.ordinalPosition - b.ordinalPosition)
        .map(column => ({
          columnName: column.columnName,
          ordinalPosition: column.ordinalPosition,
          dataType: column.dataType,
          maxLength: column.maxLength,
          characterMaxLength: column.characterMaxLength,
          precision: column.precision,
          scale: column.scale,
          isNullable: column.isNullable,
          isIdentity: column.isIdentity,
          identitySeed: column.identitySeed,
          identityIncrement: column.identityIncrement,
          isComputed: column.isComputed,
          computedExpression: column.computedExpression,
          isPersisted: column.isPersisted,
          isSparse: column.isSparse,
          isRowGuidCol: column.isRowGuidCol,
          collationName: column.collationName,
          defaultConstraintName:
            column.defaultConstraintName === null
              ? null
              : normalizeConstraintName(column.defaultConstraintName),
          defaultExpression: column.defaultExpression,
        })),
    })),

    primaryKeys: sortBy(database.primaryKeys, pk => `${pk.schemaName}.${pk.pureName}`).map(pk => ({
      constraintName: normalizeConstraintName(pk.constraintName),
      schemaName: pk.schemaName,
      pureName: pk.pureName,
      isClustered: pk.isClustered,
      columns: [...pk.columns].sort((a, b) => a.ordinalPosition - b.ordinalPosition),
    })),

    uniqueConstraints: sortBy(
      database.uniqueConstraints,
      uc => `${uc.schemaName}.${uc.pureName}.${uc.constraintName}`,
    ).map(uc => ({
      constraintName: normalizeConstraintName(uc.constraintName),
      schemaName: uc.schemaName,
      pureName: uc.pureName,
      isClustered: uc.isClustered,
      columns: [...uc.columns].sort((a, b) => a.ordinalPosition - b.ordinalPosition),
    })),

    foreignKeys: sortBy(
      database.foreignKeys,
      fk => `${fk.schemaName}.${fk.pureName}.${fk.constraintName}`,
    ).map(fk => ({
      constraintName: normalizeConstraintName(fk.constraintName),
      schemaName: fk.schemaName,
      pureName: fk.pureName,
      refSchemaName: fk.refSchemaName,
      refTableName: fk.refTableName,
      updateAction: fk.updateAction,
      deleteAction: fk.deleteAction,
      isNotTrusted: fk.isNotTrusted,
      isDisabled: fk.isDisabled,
      columns: [...fk.columns].sort((a, b) => a.ordinalPosition - b.ordinalPosition),
    })),

    checkConstraints: sortBy(
      database.checkConstraints,
      cc => `${cc.schemaName}.${cc.pureName}.${cc.constraintName}`,
    ).map(cc => ({
      constraintName: normalizeConstraintName(cc.constraintName),
      schemaName: cc.schemaName,
      pureName: cc.pureName,
      definition: cc.definition,
      isNotTrusted: cc.isNotTrusted,
      isDisabled: cc.isDisabled,
    })),

    defaultConstraints: sortBy(
      database.defaultConstraints,
      dc => `${dc.schemaName}.${dc.pureName}.${dc.columnName}`,
    ).map(dc => ({
      constraintName: normalizeConstraintName(dc.constraintName),
      schemaName: dc.schemaName,
      pureName: dc.pureName,
      columnName: dc.columnName,
      definition: dc.definition,
    })),

    indexes: sortBy(database.indexes, ix => `${ix.schemaName}.${ix.pureName}.${ix.indexName}`).map(
      index => ({
        indexName: index.indexName,
        schemaName: index.schemaName,
        pureName: index.pureName,
        indexType: index.indexType,
        isUnique: index.isUnique,
        isUniqueConstraint: index.isUniqueConstraint,
        isDisabled: index.isDisabled,
        filterDefinition: index.filterDefinition,
        columns: [...index.columns].sort((a, b) => {
          if (a.isIncluded !== b.isIncluded) return a.isIncluded ? 1 : -1;
          return a.ordinalPosition - b.ordinalPosition;
        }),
      }),
    ),

    sequences: sortBy(database.sequences, s => `${s.schemaName}.${s.pureName}`).map(sequence => ({
      schemaName: sequence.schemaName,
      pureName: sequence.pureName,
      dataType: sequence.dataType,
      // Rendered as text: these are bigints, which structuredClone-based
      // deep-equality reporting handles poorly in diff output.
      startValue: String(sequence.startValue),
      increment: String(sequence.increment),
      minValue: String(sequence.minValue),
      maxValue: String(sequence.maxValue),
      isCycling: sequence.isCycling,
      isCached: sequence.isCached,
      cacheSize: sequence.cacheSize,
      // `currentValue` is intentionally omitted: exporting a sequence's
      // current value is documented as out of scope, so a restored sequence
      // legitimately restarts from its START WITH value.
    })),

    views: sortBy(database.views, v => `${v.schemaName}.${v.pureName}`).map(view => ({
      schemaName: view.schemaName,
      pureName: view.pureName,
      definition: view.definition,
      isSchemaBound: view.isSchemaBound,
      isEncrypted: view.isEncrypted,
      usesAnsiNulls: view.usesAnsiNulls,
      usesQuotedIdentifier: view.usesQuotedIdentifier,
    })),

    routines: sortBy(database.routines, r => `${r.schemaName}.${r.pureName}`).map(routine => ({
      kind: routine.kind,
      schemaName: routine.schemaName,
      pureName: routine.pureName,
      definition: routine.definition,
      isSchemaBound: routine.isSchemaBound,
      isEncrypted: routine.isEncrypted,
      usesAnsiNulls: routine.usesAnsiNulls,
      usesQuotedIdentifier: routine.usesQuotedIdentifier,
    })),

    triggers: sortBy(
      database.triggers,
      t => `${t.schemaName}.${t.parentName}.${t.triggerName}`,
    ).map(trigger => ({
      triggerName: trigger.triggerName,
      schemaName: trigger.schemaName,
      parentName: trigger.parentName,
      definition: trigger.definition,
      isDisabled: trigger.isDisabled,
      isInsteadOf: trigger.isInsteadOf,
      events: [...trigger.events].sort(byText),
      usesAnsiNulls: trigger.usesAnsiNulls,
      usesQuotedIdentifier: trigger.usesQuotedIdentifier,
    })),
  };
}

/**
 * Normalizes generated dump text so two dumps of the *same logical* database
 * can be compared for byte equality. Only lines that legitimately differ are
 * touched: the header's database name (the target database has a different
 * name by construction) and the optional generation timestamp, plus
 * auto-generated constraint names appearing in DDL.
 */
export function normalizeDumpText(sql: string): string {
  return sql
    .split(/\r?\n/)
    .filter(line => !line.startsWith('-- Database:') && !line.startsWith('-- Generated:'))
    .join('\n')
    .replace(/\b(DF|PK|UQ|CK|FK)__[A-Za-z0-9_@#$]*__[0-9A-F]{8}\b/g, '$1__<auto-generated>');
}
